### ISSUE TITLE
YN0001: │ HTTPError: @oswee/test-npm-private-package@npm:0.0.7: Response code 404 (Not Found)

### ISSUE THREAD

**Issue by dzintars** [dzintars/front#124]
Yarn is failing to install the package from GitHub registry.
My project level `./.npmrc` contains single line: `@oswee:registry = https://npm.pkg.github.com/`.
User level `~/.npmrc` contains `//npm.pkg.github.com/:_authToken=${GITHUB_NPM_PAT}` and `${GITHUB_NPM_PAT}` environment variable is set and accessible. Actual package is not private.

```sh
» yarn add @oswee/test-npm-private-package@0.0.7
➤ YN0000: ┌ Resolution step
➤ YN0001: │ HTTPError: @oswee/test-npm-private-package@npm:0.0.7: Response code 404 (Not Found)
    at s.<anonymous> (/home/dzintars/code/github.com/dzintars/front/.yarn/releases/yarn-berry.js:23:36333)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
➤ YN0000: └ Completed
➤ YN0000: Failed with errors in 0.2s
```

**Comment by dzintars** [comment]
Why before version number there is that `npm:` prefix in the output?

**Comment by dzintars** [comment]
https://github.com/yarnpkg/berry/issues/1740

**Comment by dzintars** [comment]
https://github.com/dzintars/front/commit/a25a9b280634a8bb8f13098664a6b7fa42ddcd1b seems fixing public package import. Private packages still not accessible.

**Comment by dzintars** [comment]
OK. Finally booth private and public packages can be installed. bd7347cbfa7841df64d43943c87829e95b91622b
