### ISSUE TITLE
TypeError: Cannot add property htmlWebpackPluginAlterChunks, object is not extensible

### ISSUE THREAD

**Issue by dzintars** [dzintars/front#45]
After upgrading to WebPack 5 `yarn add -D webpack@next` (5.0.0-beta.21) getting this error:

```sh
TypeError: Cannot add property htmlWebpackPluginAlterChunks, object is not extensible
    at /home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/html-webpack-plugin-virtual-a5bdd68bbb/0/cache/html-webpack-plugin-npm-3.2.0-a2925f8583-02dcb274a8.zip/node_modules/html-webpack-plugin/index.js:59:56
    at Hook.eval (eval at create (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/webpack-npm-5.0.0-beta.21-0d53dcfb50-e8ae181bba.zip/node_modules/webpack/lib/Compiler.js:869:26)
    at /home/dzintars/code/github.com/dzintars/front/.yarn/cache/webpack-npm-5.0.0-beta.21-0d53dcfb50-e8ae181bba.zip/node_modules/webpack/lib/Compiler.js:910:29
    at Hook.eval [as callAsync] (eval at create (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/webpack-npm-5.0.0-beta.21-0d53dcfb50-e8ae181bba.zip/node_modules/webpack/lib/Compiler.js:905:28)
    at /home/dzintars/code/github.com/dzintars/front/.yarn/cache/webpack-npm-5.0.0-beta.21-0d53dcfb50-e8ae181bba.zip/node_modules/webpack/lib/Watching.js:112:19
    at Hook.eval [as callAsync] (eval at create (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
```

**Comment by linuxonrails** [comment]
Same problem.

**Comment by Iodine-** [comment]
`html-webpack-plugin` likely needs to be updated to work with webpack 5.  For now you can use @ScriptedAlchemy fork here [https://github.com/ScriptedAlchemy/html-webpack-plugin#master ](https://github.com/ScriptedAlchemy/html-webpack-plugin#master)

**Comment by dzintars** [comment]
@lodine- Thank you for commenting on this. :) Will try this a bit later.

**Comment by dzintars** [comment]
> `html-webpack-plugin` likely needs to be updated to work with webpack 5. For now you can use @ScriptedAlchemy fork here [https://github.com/ScriptedAlchemy/html-webpack-plugin#master ](https://github.com/ScriptedAlchemy/html-webpack-plugin#master)

Thank you for commenting on this. :) Will try this a bit later.

**Comment by kowalk** [comment]
Same problem here - I'm using mentioned fork repo as a workaround for now

**Comment by ScriptedAlchemy** [comment]
Omg you're using my fork. I'll rebase off the main project and repatch. Didn't realize others use my fork. I'll push to mom as well

**Comment by Iodine-** [comment]
@ScriptedAlchemy: landed on this is a workaround as a lot of the examples out there use your fork - `html-webpack-plugin@next` has wp5 support, so people should likely be using that instead of your fork now.

@kowalk - `html-webpack-plugin@next` has webpack 5 support now, so you should give that a go first.

**Comment by ScriptedAlchemy** [comment]
Okay thank god. I myself am using the non forked html webpack plug-in and it's working just fine plus works with module federation.

**Comment by kowalk** [comment]
@lodine thanks!

**Comment by evyros** [comment]
I got here from google because I got the same error.
After upgrading to `html-webpack-plugin@next`, I get the following when I use `template`:
```
ERROR in   Error: The loader "/Users/[xxx]/Desktop/canv-sdk/index.html" didn't return html.
  
  - index.js:137 HtmlWebpackPlugin.evaluateCompilationResult
    [canv-sdk]/[html-webpack-plugin]/index.js:137:24
  
  - index.js:323 
    [canv-sdk]/[html-webpack-plugin]/index.js:323:26
  
  - task_queues.js:97 processTicksAndRejections
    internal/process/task_queues.js:97:5
  
  - async Promise.all
  
  - async Promise.all
  
webpack 5.4.0 compiled with 1 error in 4099 ms
```
It works only if I use `templateContent` (and yes, I checked the path).
My webpack config is pretty clean & simple:
```javascript
module.exports = {
	entry: './src/index.ts',
	output: {
		path: path.resolve(__dirname, 'dist'),
		filename: 'scripts.min.js'
	},
	module: {
		rules: [
			{
				use: 'ts-loader',
				exclude: /node_modules/
			}
		]
	},
	resolve: {
		extensions: ['.ts', '.js'],
	},
	plugins: [
		new HtmlWebpackPlugin({ template: 'index.html' }),
	],
	mode: 'development',
	devtool: 'source-map',
	devServer: {
		contentBase: path.join(__dirname, 'dist'),
		compress: true,
		port: 9000
	},
};
```
Hopefully you'll get to it soon, because this preventing me from upgrading to webpack 5.

**Comment by factormaarten** [comment]
I'm unfortunately still getting this error using webpack 5.67.0 and html-webpack-plugin 5.5.0 Also @ScriptedAlchemy his fork does not work for me.

```
9% setup compilation HtmlWebpackPluginHooksTypeError: Cannot add property htmlWebpackPluginAlterChunks, object is not extensible
    at /home/maarten/Documents/Projects/storefront/vue-storefront/core/node_modules/html-webpack-plugin/index.js:59:56
    at Hook.eval (eval at create (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:194:1)
    at Hook.CALL_DELEGATE [as _call] (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/lib/Compiler.js:1109:26)
    at /home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/lib/Compiler.js:1153:29
    at Hook.eval [as callAsync] (eval at create (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/lib/Compiler.js:1148:28)
    at /home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/lib/Compiler.js:524:12
    at Compiler.readRecords (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/lib/Compiler.js:973:5)
    at /home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/lib/Compiler.js:521:11
    at Hook.eval [as callAsync] (eval at create (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at /home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/lib/Compiler.js:518:20
    at Hook.eval [as callAsync] (eval at create (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at run (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/lib/Compiler.js:515:25)
    at Compiler.run (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/lib/Compiler.js:538:4)
    at processOptions (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack-cli/bin/cli.js:353:14)
    at /home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack-cli/bin/cli.js:364:3
    at Object.parse (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack-cli/node_modules/yargs/yargs.js:567:18)
    at /home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack-cli/bin/cli.js:49:8
    at Object.<anonymous> (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack-cli/bin/cli.js:366:3)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at runCli (/home/maarten/Documents/Projects/storefront/vue-storefront/node_modules/webpack/bin/webpack.js:69:2)
```

What else can possibly be wrong?
