### ISSUE TITLE
Error: Qualified path resolution failed - none of the candidates can be found on the disk.

### ISSUE THREAD

**Issue by dzintars** [dzintars/front#46]
After upgrading to webpack@next and webpack-cli@beta getting this error on `yarn start`:

```sh
» yarn start                  
/home/dzintars/code/github.com/dzintars/front/.pnp.js:16788
    throw firstError;
    ^

Error: Qualified path resolution failed - none of the candidates can be found on the disk.

Source path: /home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/webpack-cli-virtual-6a2b4a2266/0/cache/webpack-cli-npm-4.0.0-beta.8-639c7f60d2-f012b213b4.zip/node_modules/webpack-cli/bin/config-yargs
Rejected candidate: /home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/webpack-cli-virtual-6a2b4a2266/0/cache/webpack-cli-npm-4.0.0-beta.8-639c7f60d2-f012b213b4.zip/node_modules/webpack-cli/bin/config-yargs
Rejected candidate: /home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/webpack-cli-virtual-6a2b4a2266/0/cache/webpack-cli-npm-4.0.0-beta.8-639c7f60d2-f012b213b4.zip/node_modules/webpack-cli/bin/config-yargs.js
Rejected candidate: /home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/webpack-cli-virtual-6a2b4a2266/0/cache/webpack-cli-npm-4.0.0-beta.8-639c7f60d2-f012b213b4.zip/node_modules/webpack-cli/bin/config-yargs.json
Rejected candidate: /home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/webpack-cli-virtual-6a2b4a2266/0/cache/webpack-cli-npm-4.0.0-beta.8-639c7f60d2-f012b213b4.zip/node_modules/webpack-cli/bin/config-yargs.node

Require stack:
- /home/dzintars/code/github.com/dzintars/front/.yarn/unplugged/webpack-dev-server-virtual-85423d99a7/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at internalTools_makeError (/home/dzintars/code/github.com/dzintars/front/.pnp.js:16533:34)
    at resolveUnqualified (/home/dzintars/code/github.com/dzintars/front/.pnp.js:17524:13)
    at resolveRequest (/home/dzintars/code/github.com/dzintars/front/.pnp.js:17548:14)
    at Object.resolveRequest (/home/dzintars/code/github.com/dzintars/front/.pnp.js:17608:26)
    at Function.external_module_.Module._resolveFilename (/home/dzintars/code/github.com/dzintars/front/.pnp.js:16765:34)
    at Function.external_module_.Module._load (/home/dzintars/code/github.com/dzintars/front/.pnp.js:16629:48)
    at Module.require (internal/modules/cjs/loader.js:1090:19)
    at require (internal/modules/cjs/helpers.js:75:18)
    at Object.<anonymous> (/home/dzintars/code/github.com/dzintars/front/.yarn/unplugged/webpack-dev-server-virtual-85423d99a7/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:1201:30)
```

**Comment by dzintars** [comment]
Seems to me that simple `yarn cache clean --all` and `yarn install` solved this issue. At least in 0.1.0.

**Comment by dzintars** [comment]
For Webpack 5 setup seems it's is required to downgrade webpack-cli `yarn add -D webpack-cli@3`

https://github.com/webpack/webpack-dev-server/issues/2029
https://github.com/yarnpkg/berry/issues/1554

**Comment by dzintars** [comment]
For Webpack 5 setup seems it's is required to downgrade webpack-cli `yarn add -D webpack-cli@3`

https://github.com/webpack/webpack-dev-server/issues/2029
https://github.com/yarnpkg/berry/issues/1554
