### ISSUE TITLE
TypeError: Cannot add property htmlWebpackPluginAlterChunks, object is not extensible

### ISSUE THREAD

**Issue by dzintars** [dzintars/front#47]
```sh
» yarn start               
TypeError: Cannot add property htmlWebpackPluginAlterChunks, object is not extensible
    at /home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/html-webpack-plugin-virtual-a5bdd68bbb/0/cache/html-webpack-plugin-npm-3.2.0-a2925f8583-02dcb274a8.zip/node_modules/html-webpack-plugin/index.js:59:56
    at Hook.eval (eval at create (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/webpack-npm-5.0.0-beta.21-0d53dcfb50-e8ae181bba.zip/node_modules/webpack/lib/Compiler.js:869:26)
    at /home/dzintars/code/github.com/dzintars/front/.yarn/cache/webpack-npm-5.0.0-beta.21-0d53dcfb50-e8ae181bba.zip/node_modules/webpack/lib/Compiler.js:910:29
    at Hook.eval [as callAsync] (eval at create (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/webpack-npm-5.0.0-beta.21-0d53dcfb50-e8ae181bba.zip/node_modules/webpack/lib/Compiler.js:905:28)
    at /home/dzintars/code/github.com/dzintars/front/.yarn/cache/webpack-npm-5.0.0-beta.21-0d53dcfb50-e8ae181bba.zip/node_modules/webpack/lib/Watching.js:112:19
    at Hook.eval [as callAsync] (eval at create (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:15:1)
```

**Comment by dzintars** [comment]
Seems that `yarn add -D html-webpack-plugin@next` solves this issue.
https://github.com/webpack/webpack/issues/8537
