### ISSUE TITLE
TypeError: Cannot read property 'get' of undefined

### ISSUE THREAD

**Issue by dzintars** [dzintars/front#48]
```sh
/home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/html-webpack-plugin-virtual-37526ef476/0/cache/html-webpack-plugin-npm-4.0.0-beta.14-bdc493e01b-1d8da76df4.zip/node_modules/html-webpack-plugin/lib/compiler.js:340
  const isCacheOutOfDate = childCompiler.fileDependencies.some((fileDependency) => {
                                                          ^
TypeError: Cannot read property 'get' of undefined
    at /home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/html-webpack-plugin-virtual-37526ef476/0/cache/html-webpack-plugin-npm-4.0.0-beta.14-bdc493e01b-1d8da76df4.zip/node_modules/html-webpack-plugin/lib/compiler.js:341:38
    at Array.some (<anonymous>)
    at isChildCompilerCacheOutdated (/home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/html-webpack-plugin-virtual-37526ef476/0/cache/html-webpack-plugin-npm-4.0.0-beta.14-bdc493e01b-1d8da76df4.zip/node_modules/html-webpack-plugin/lib/compiler.js:340:59)
    at Object.hasOutDatedTemplateCache (/home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/html-webpack-plugin-virtual-37526ef476/0/cache/html-webpack-plugin-npm-4.0.0-beta.14-bdc493e01b-1d8da76df4.zip/node_modules/html-webpack-plugin/lib/compiler.js:321:16)
    at /home/dzintars/code/github.com/dzintars/front/.yarn/$$virtual/html-webpack-plugin-virtual-37526ef476/0/cache/html-webpack-plugin-npm-4.0.0-beta.14-bdc493e01b-1d8da76df4.zip/node_modules/html-webpack-plugin/index.js:136:25
    at Hook.eval (eval at create (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:7:1)
    at Compiler.newCompilation (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/webpack-npm-5.0.0-beta.21-0d53dcfb50-e8ae181bba.zip/node_modules/webpack/lib/Compiler.js:868:30)
    at /home/dzintars/code/github.com/dzintars/front/.yarn/cache/webpack-npm-5.0.0-beta.21-0d53dcfb50-e8ae181bba.zip/node_modules/webpack/lib/Compiler.js:910:29
    at Hook.eval [as callAsync] (eval at create (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/tapable-npm-2.0.0-beta.11-fb6235fada-e4c750918a.zip/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Compiler.compile (/home/dzintars/code/github.com/dzintars/front/.yarn/cache/webpack-npm-5.0.0-beta.21-0d53dcfb50-e8ae181bba.zip/node_modules/webpack/lib/Compiler.js:905:28)
```

**Comment by dzintars** [comment]
DEP_WEBPACK_MAIN_TEMPLATE_GET_ASSET_PATH - terser-webpack-plugin ???
DEP_WEBPACK_DEPRECATION_ARRAY_TO_SET - ts-loader https://github.com/TypeStrong/ts-loader/issues/1126 ???
